export const OPEN_CONTACT_DELETE_MODAL = 'OPEN_CONTACT_DELETE_MODAL';
export const CLOSE_CONTACT_DELETE_MODAL = 'CLOSE_CONTACT_DELETE_MODAL';
export const OPEN_LOCATION_DELETE_MODAL = 'OPEN_LOCATION_DELETE_MODAL';
export const CLOSE_LOCATION_DELETE_MODAL = 'CLOSE_LOCATION_DELETE_MODAL';
export const MOVE_TO_CONTACTS_PAGE = 'MOVE_TO_CONTACTS_PAGE';
export const MOVE_TO_LOCATIONS_PAGE = 'MOVE_TO_LOCATIONS_PAGE';