export const OPEN_DELETE_MODAL = 'OPEN_DELETE_MODAL';
export const CLOSE_DELETE_MODAL = 'CLOSE_DELETE_MODAL';
export const MOVE_TO_CONTACTS_PAGE = 'MOVE_TO_CONTACTS_PAGE';
export const MOVE_TO_LOCATIONS_PAGE = 'MOVE_TO_LOCATIONS_PAGE';
export const CITY_CHANGED = 'CITY_CHANGED';